pi=input('enter a prime number:\n');
gi=input('enter another prime number{gerater than the previous one}');
g=int(gi);
p=int(pi);
a=6;
b=9;
#ya=(g^a)%p;
#yb=(g^b)%p;
ya=(g^a);
yb=(g^b);

secretkey1=(yb^a)%p;
secretkey2=(ya^b)%p;
print('the secret key generated by alice is:\n',secretkey1)
print('the secret key generated by bob is:\n',secretkey2)
