import math;
p=input('enter a prime number: ');
g=input('enter another prime number which is greater than the previous one : ');
a=9;
b=3;
ya=math.fmod((math.pow(p,a)),g);
yb=math.pow(p,b)%g;
print ya;
print yb;
secretkey1=math.pow(yb,a)%g;
secretkey2=(math.pow(ya,b))%g;
print("The secret key generated by alice is: %d" % secretkey1)
print("\nThe secret key generated by bob is: %d" % secretkey2)
